config/routes.rb
Rails.application.routes.draw do
  get 'administrator/index'

  get 'administrator' => 'administrator#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
 
  resources :admins
  scope '(:locale)' do
    resources :orders
    resources :lina_items
    resources :carts
    root 'store#index'
    get 'store/index'
  end
  

  

  resources :products do
    get :who_bought, on: :member
  end
  resources :lina_items do
    put 'decrement', on: :member
  end

end

app/views/admins/_form.html.haml
= simple_form_for(@admin) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, size: 40
    = f.password_field :password, size: 40
    = f.password_field :pssword_confirmation, size: 40
  .form-actions
    = f.button :submit

app/views/admins/edit.html.haml
%h1 Editing admin

= render 'form'

= link_to 'Show', @admin
\|
= link_to 'Back', admins_path

app/views/admins/index.html.haml
%h1 Listing admins
- if notice
  %p#notice= notice
%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th
      %th

  %tbody
    - @admins.each do |admin|
      %tr
        %td= admin.name
        %td= link_to 'Show', admin
        %td= link_to 'Edit', edit_admin_path(admin)
        %td= link_to 'Destroy', admin, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Admin', new_admin_path

app/views/admins/new.html.haml
%h1 New admin

= render 'form'

= link_to 'Back', admins_path

app/views/admins/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @admin.name
%p
  %b Password:
  = @admin.password

= link_to 'Edit', edit_admin_path(@admin)
\|
= link_to 'Back', admins_path