config/routes.rb
Rails.application.routes.draw do
  get 'administrator/index'

  get 'administrator' => 'administrator#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
 
  resources :admins
  scope '(:locale)' do
    resources :orders
    resources :lina_items
    resources :carts
    root 'store#index'
    get 'store/index'
  end
  

  

  resources :products do
    get :who_bought, on: :member
  end
  resources :lina_items do
    put 'decrement', on: :member
  end

end

app/models/lina_item.rb
class LinaItem < ActiveRecord::Base
	validates :product, presence: true
	belongs_to :order
	belongs_to :product
	belongs_to :cart

	def total_price
		product.price * quantity
	end

end

app/controllers/lina_items_controller.rb
class LinaItemsController < ApplicationController
  include CurrentCart
  
  before_action :set_cart, only: [:create, :decrement]
  before_action :set_lina_item, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:create, :decrement]

  # GET /lina_items
  # GET /lina_items.json
  def index
    @lina_items = LinaItem.all
  end

  # GET /lina_items/1
  # GET /lina_items/1.json
  def show
  end

  # GET /lina_items/new
  def new
    @lina_item = LinaItem.new
  end

  # GET /lina_items/1/edit
  def edit
  end

  # POST /lina_items
  # POST /lina_items.json
  def create

    product = Product.find(params[:product_id])
    @lina_item = @cart.add_product(product.id)

    respond_to do |format|
      if @lina_item.save
        format.html { redirect_to root_url }
        format.js
        format.json { render :show, status: :created, location: @lina_item }
      else
        format.html { render :new }
        format.json { render json: @lina_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lina_items/1
  # PATCH/PUT /lina_items/1.json
  def update

    respond_to do |format|
      if @lina_item.update(lina_item_params)
        format.html { redirect_to @lina_item, notice: 'Lina item was successfully updated.' }
        format.json { render :show, status: :ok, location: @lina_item }
      else
        format.html { render :edit }
        format.json { render json: @lina_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def decrement

    @lina_item = @cart.decrement(params[:id])

    respond_to do |format|
      if @lina_item.save
        format.html { redirect_to root_url, notice: 'Line item was successfully updated.' }
        format.js   { @current_item = @lina_item }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @lina_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lina_items/1
  # DELETE /lina_items/1.json
  def destroy
    #@lina_item = LinaItem.find(params[:id])
    #if @lina_item.quantity > 1
    #  @lina_item.update_attributes(:quantity => @lina_item.quantity - 1)
    #else
    #  @lina_item.destroy
    #end 

    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lina_item
      @lina_item = LinaItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lina_item_params
      params.require(:lina_item).permit(:product_id)
    end
end

app/helpers/lina_items_helper.rb
module LinaItemsHelper
end

app/views/lina_items/_form.html.haml
= simple_form_for(@lina_item) do |f|
  = f.error_notification

  .form-inputs
    = f.association :product
    = f.association :cart

  .form-actions
    = f.button :submit

app/views/lina_items/_lina_item.html.haml
%tr
	%td
		= lina_item.quantity 
		\x
	%td= lina_item.product.name
	%td.item_price= number_to_currency(lina_item.total_price)
	%td= link_to t('.delete'), decrement_lina_item_path(lina_item), method: :put, remote: true

app/views/lina_items/_lina_item.text.haml
= sprintf("%2d x %s", lina_item.quantity, truncate(lina_item.product.name, length: 50))

app/views/lina_items/create.js.erb
$('#notice').hide();

if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000); }

$('#cart').html("<%= escape_javascript render(@cart) %>");

app/views/lina_items/decrement.js.erb
$('#cart').html("<%=j render @cart %>");
$('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#114411'}, 1000);
if ($('#cart tr').length==1) {
    // Hide the cart
    $('#cart').hide('blind', 1000);    
}

app/views/lina_items/edit.html.haml
%h1 Editing lina_item

= render 'form'

= link_to 'Show', @lina_item
\|
= link_to 'Back', lina_items_path

app/views/lina_items/index.html.haml
%h1 Listing lina_items

%table
  %thead
    %tr
      %th Product
      %th Cart
      %th
      %th
      %th

  %tbody
    - @lina_items.each do |lina_item|
      %tr
        %td= lina_item.product
        %td= lina_item.cart
        %td= link_to 'Show', lina_item
        %td= link_to 'Edit', edit_lina_item_path(lina_item)
        %td= link_to 'Destroy', lina_item, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Lina item', new_lina_item_path

app/views/lina_items/new.html.haml
%h1 New lina_item

= render 'form'

= link_to 'Back', lina_items_path

app/views/lina_items/show.html.haml
%p#notice= notice

%p
  %b Product:
  = @lina_item.product
%p
  %b Cart:
  = @lina_item.cart

= link_to 'Edit', edit_lina_item_path(@lina_item)
\|
= link_to 'Back', lina_items_path