config/routes.rb
Rails.application.routes.draw do
  get 'administrator/index'

  get 'administrator' => 'administrator#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
 
  resources :admins
  scope '(:locale)' do
    resources :orders
    resources :lina_items
    resources :carts
    root 'store#index'
    get 'store/index'
  end
  

  

  resources :products do
    get :who_bought, on: :member
  end
  resources :lina_items do
    put 'decrement', on: :member
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArcheryStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
	<div class="container">

	<p style="color: red;"><%= flash[:error] %></p>
	<p style="color: green;"><%= flash[:success] %></p> 
<%= render 'shared/navbar' %>
	</div>
  <div id="columns">
    <div id="side">

        <div id="cart">
          <%= render @cart %>
        </div>


      <% if session[:admin_id] %>
        <ul>
          <li><%= link_to 'Заказы', orders_path %></li>
          <li><%= link_to 'Товары', products_path %></li>
          <li><%= link_to 'Администраторы', admins_path %></li>
        </ul>
        <%= button_to 'Выйти', logout_path, method: :delete %>
        <% end %>
      
    </div>
    <div id="main">
<%= yield %>
</div>

</body>
</html>